# WARNING: DO NOT EDIT THIS FILE, IT IS MANAGED BY ANSIBLE-SERVICES-FRAMEWORK.
"""
ASGI config for unified_inventory_service.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "unified_inventory_service.settings")

application = get_asgi_application()
