# Framework protected files
# These files are fully maintained and managed by the framework and should not be modified
# in repositories using the template

protected_files:
  - inventory_service/
  - .github/workflows/framework-validation.yml
  - .github/workflows/framework-update.yml
  - .github/rulesets/branch-protection.json
  - manage.py
  - sonar-project.properties
  - LICENSE
