# =============================================================================
# DEVELOPMENT ONLY - DO NOT USE IN PRODUCTION
# =============================================================================
# This manifest is for local development and testing only.
# It uses DEBUG=true, emptyDir volumes, and is not suitable for production.
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: localhost:5001/inventory-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: INVENTORY_SERVICE_ALLOWED_HOSTS
              value: '["*"]'
            - name: INVENTORY_SERVICE_DEBUG
              value: "true"
            - name: INVENTORY_SERVICE_DATABASES__default__NAME
              value: "/app/data/db.sqlite3"
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /ping/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: sqlite-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
