# WARNING: DO NOT EDIT THIS FILE, IT IS MANAGED BY ANSIBLE-SERVICES-FRAMEWORK.
"""
URL configuration for inventory_service.

This file is managed by the platform-service-framework and should not be edited
directly. For custom URL patterns, use `apps/urls.py` or individual app urls.py.

## LOADED_APPS Mechanism

The framework dynamically discovers and loads URL patterns from apps:

1. **App registration**: Apps are registered in `apps/settings.py` under the
   `project_applications` list (e.g., `["apps.core", "apps.api"]`).

2. **Discovery**: At runtime, the framework filters `INSTALLED_APPS` for entries
   that start with `apps.` and have a corresponding directory in the apps folder.

3. **LOADED_APPS population**: The filtered list becomes `settings.LOADED_APPS`,
   preserving the order defined in `project_applications`.

4. **URL loading**: The framework iterates through LOADED_APPS and imports each
   app's `urls.py`, appending patterns to the main urlpatterns.

## Full URL Loading Order

Django uses first-match routing, so loading order determines which pattern
handles a request when multiple patterns could match.

1. Django Ansible Base URLs (DAB)
2. Dynamic API root view overrides
3. Cross-app/custom URL patterns (`apps/urls.py`)
4. Individual app URL patterns (order from `project_applications` in `apps/settings.py`)
5. Debug/development URLs

## Controlling URL Loading Order

**Example conflict**: If both `apps.core` and `apps.api` define a pattern for
`api/v1/users/`, only the first-loaded app's pattern will handle requests.
The other pattern becomes unreachable.

You have two options to control this:

### Option 1: Reorder apps in `project_applications`

The URL loading order follows the order in `project_applications` in
`apps/settings.py`. Reordering apps there changes their URL loading order.

- If `project_applications = ["apps.core", "apps.api"]`, core's URLs load first
- If two apps define the same URL pattern, the first one in the list wins

**Trade-offs**:
- Changing app order affects settings loading order (each app's `settings.py`
  is loaded in this order)
- This changes URL loading order for ALL URLs in the app - you cannot load
  a single URL from app B before app A while keeping the rest of app B after

Use this when you want to change the overall priority of an entire app.

### Option 2: Use `apps/urls.py`

The `apps/urls.py` file loads BEFORE all individual app URL patterns, giving
you a way to define URLs that are independent of app order. This provides
finer control:

- Add a single high-priority URL without reordering apps
- Define URLs that don't belong to any specific app
- Override patterns from any app regardless of app order

Use this for service-level customizations, cross-app endpoints, or when you
need a specific URL to take priority without changing app order.

## Where to Add URLs

| Use Case | Location |
|----------|----------|
| App-specific endpoints | `apps/<app_name>/urls.py` |
| Service-level customizations | `apps/urls.py` |
| Priority/override patterns | `apps/urls.py` |
| Cross-app endpoints | `apps/urls.py` |

"""

import importlib

from ansible_base.lib.dynamic_config.dynamic_urls import (
    api_urls,  # type: ignore
    api_version_urls,  # type: ignore
    root_urls,  # type: ignore
)
from ansible_base.rbac.service_api.urls import rbac_service_urls
from ansible_base.resource_registry.urls import urlpatterns as resource_api_urls
from django.conf import settings
from django.urls import include, path

from apps.core.views import APIRootView

urlpatterns = []

# Django Ansible Base URLs
urlpatterns += [
    path("api/v1/", include(api_version_urls)),
    path("api/v1/", include(resource_api_urls)),
    path("api/v1/", include(rbac_service_urls)),
    path("api/", include(api_urls)),
    path("", include(root_urls)),
]

# Override empty router views from DAB with dynamic API root
urlpatterns += [
    path("api/v1/", APIRootView.as_view(view_name="v1"), name="api-v1-index"),
    path("api/", APIRootView.as_view(view_name="api"), name="api-index"),
    path("", APIRootView.as_view(view_name="root"), name="root-index"),
]

# Extend URL patterns from apps/urls.py
urlpatterns += [path("", include("apps.urls"))]

# Extend URL patterns for each app
for app in settings.LOADED_APPS:
    app_name = app.split(".")[-1]
    url_module_path = f"{app}.urls"
    urls = importlib.import_module(url_module_path)
    if patterns := getattr(urls, "urlpatterns", None):
        urlpatterns.append(path("", include(url_module_path)))

# Debug and Development URLS
if not settings.DYNACONF.get("IS_RUNNING_TESTS") and settings.DYNACONF.get("DEBUG"):
    try:
        from debug_toolbar.toolbar import debug_toolbar_urls  # noqa

        urlpatterns.extend(debug_toolbar_urls())
    except ImportError:
        pass  # debug_toolbar not installed

# DRF Browsable API Login URL
urlpatterns += [
    path("api-auth/", include("rest_framework.urls")),
]
