# Generated by Django 5.2.11 on 2026-02-18 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0006_add_physical_server_orchestration_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDrift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drift_type', models.CharField(choices=[('modified', 'Modified'), ('deleted', 'Deleted'), ('restored', 'Restored')], db_index=True, max_length=16)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='modified: {field: {from: old, to: new}} for every changed field. deleted/restored: snapshot of key field values at event time.')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='collectionrun',
            new_name='inventory_c_provide_91f128_idx',
            old_name='inventory_cr_provider_time_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionrun',
            new_name='inventory_c_status_7b90a1_idx',
            old_name='inventory_cr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionrun',
            new_name='inventory_c_task_uu_73ebad_idx',
            old_name='inventory_c_task_uu_idx',
        ),
        migrations.RenameIndex(
            model_name='provider',
            new_name='inventory_p_vendor_9fbc85_idx',
            old_name='inventory_p_vendor_idx',
        ),
        migrations.RenameIndex(
            model_name='provider',
            new_name='inventory_p_infrast_f465bb_idx',
            old_name='inventory_p_infra_vendor_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_resourc_8568bd_idx',
            old_name='inventory_r_type_state_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_provide_41a108_idx',
            old_name='inventory_r_provider_type_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_organiz_44d613_idx',
            old_name='inventory_r_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_region_9a8f2c_idx',
            old_name='inventory_r_region_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_vendor__8abaf9_idx',
            old_name='inventory_r_vendor_type_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_canonic_5b8a42_idx',
            old_name='inventory_r_canonic_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_seen_co_c4cdd4_idx',
            old_name='inventory_r_seen_co_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='inventory_r_last_se_b58759_idx',
            old_name='inventory_r_last_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcemetric',
            new_name='inventory_r_resourc_62e176_idx',
            old_name='inventory_rm_res_type_time_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcemetric',
            new_name='inventory_r_metric__77df5b_idx',
            old_name='inventory_rm_type_time_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcerelationship',
            new_name='inventory_r_source__2e0f4a_idx',
            old_name='inventory_rr_source_type_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcerelationship',
            new_name='inventory_r_target__607e33_idx',
            old_name='inventory_rr_target_type_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcesighting',
            new_name='inventory_r_resourc_ec6867_idx',
            old_name='inventory_r_resourc_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcesighting',
            new_name='inventory_r_collect_162493_idx',
            old_name='inventory_r_collect_run_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcesighting',
            new_name='inventory_r_state_1e801e_idx',
            old_name='inventory_r_sighting_state_idx',
        ),
        migrations.AddField(
            model_name='resource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this resource was detected missing from the provider. NULL means currently present. Set during collection when a previously-known resource is absent from the current run.', null=True),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='ansible_collection',
            field=models.CharField(blank=True, default='', help_text='Ansible collection used for this run.', max_length=256),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='collector_version',
            field=models.CharField(blank=True, default='', help_text='Version of the collection plugin/module that ran.', max_length=64),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='job_id',
            field=models.CharField(blank=True, default='', help_text='AAP Job ID that triggered this collection.', max_length=256),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='target_resource_types',
            field=models.JSONField(blank=True, default=list, help_text='List of resource_type slugs targeted. Empty means full refresh.'),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='description',
            field=models.TextField(blank=True, default='', help_text='What this property represents and how collectors should populate it.'),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='example_value',
            field=models.CharField(blank=True, default='', help_text="Example value for documentation (e.g. 'true', '4096', 'guestToolsRunning').", max_length=512),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='key',
            field=models.CharField(help_text="The JSONB key name that collectors should use in Resource.properties (e.g. 'linked_clone', 'tools_status').", max_length=128),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='name',
            field=models.CharField(help_text="Human-readable name (e.g. 'Linked Clone', 'VMware Tools Status').", max_length=256),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='required',
            field=models.BooleanField(default=False, help_text='Whether collectors MUST populate this property. Optional properties are documented but not enforced.'),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='value_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('datetime', 'DateTime (ISO 8601)'), ('json', 'JSON object/array')], default='string', help_text='Expected data type for this property value.', max_length=16),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='vendor_scope',
            field=models.CharField(blank=True, default='', help_text="If set, this property only applies to a specific vendor (e.g. 'vmware', 'aws'). Empty means it applies to all vendors.", max_length=64),
        ),
        migrations.AlterField(
            model_name='provider',
            name='connection_config',
            field=models.JSONField(blank=True, default=dict, help_text='Vendor-specific connection parameters (region, zone, tenant, etc.).'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='credential_ref',
            field=models.CharField(blank=True, default='', help_text='External credential reference (AAP credential ID, vault path, etc.).', max_length=512),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(blank=True, default='', help_text="Specific manager type within the vendor (e.g. 'ec2', 'vcenter', 'aci').", max_length=64),
        ),
        migrations.AlterField(
            model_name='provider',
            name='vendor',
            field=models.CharField(db_index=True, help_text="Vendor slug matching the Ansible collection namespace (e.g. 'aws', 'vmware', 'cisco').", max_length=64),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ansible_connection',
            field=models.CharField(blank=True, default='', help_text='Connection type (ssh, winrm, network_cli, httpapi, etc.).', max_length=64),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ansible_host',
            field=models.CharField(blank=True, default='', help_text='The ansible_host value for this resource.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='resource',
            name='availability_zone',
            field=models.CharField(blank=True, default='', help_text='Availability zone or rack location.', max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='collection_run',
            field=models.ForeignKey(blank=True, help_text='The collection run that last updated this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='inventory.collectionrun'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cpu_count',
            field=models.IntegerField(blank=True, help_text='Number of vCPUs / cores (compute resources only).', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ems_ref',
            field=models.CharField(db_index=True, help_text='Provider-native unique reference (ManageIQ: ems_ref). E.g. AWS instance ID, vSphere MOID, Cisco serial number.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='resource',
            name='first_discovered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this resource was first discovered.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fqdn',
            field=models.CharField(blank=True, default='', help_text='Fully Qualified Domain Name.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='resource',
            name='inventory_group',
            field=models.CharField(blank=True, default='', help_text='Primary Ansible inventory group this resource belongs to.', max_length=512),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ip_addresses',
            field=models.JSONField(blank=True, default=list, help_text='List of IP addresses associated with this resource.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_job_id',
            field=models.CharField(blank=True, default='', help_text='ID of the last AAP job that touched this resource.', max_length=256),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, help_text='When this resource was last seen in a collection run.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mac_addresses',
            field=models.JSONField(blank=True, default=list, help_text='List of MAC addresses.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='memory_mb',
            field=models.IntegerField(blank=True, help_text='Memory in MB (compute resources only).', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this resource.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='os_name',
            field=models.CharField(blank=True, default='', help_text="Full OS name (e.g. 'Red Hat Enterprise Linux 9.2', 'NX-OS 10.3').", max_length=256),
        ),
        migrations.AlterField(
            model_name='resource',
            name='os_type',
            field=models.CharField(blank=True, default='', help_text='Normalized OS family (linux, windows, network_os, storage_os).', max_length=64),
        ),
        migrations.AlterField(
            model_name='resource',
            name='power_state',
            field=models.CharField(blank=True, default='', help_text='Power state for compute resources (on, off, suspended).', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text="Type-specific and vendor-specific attributes (JSONB). This is the Level 3 'Device Properties' from the taxonomy."),
        ),
        migrations.AlterField(
            model_name='resource',
            name='provider',
            field=models.ForeignKey(help_text='The provider this resource was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='inventory.provider'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='provider_tags',
            field=models.JSONField(blank=True, default=dict, help_text='Tags/labels from the provider (key-value pairs).'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cloud region, datacenter, or site.', max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(help_text='Normalized resource type from the taxonomy.', on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='inventory.resourcetype'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('stopped', 'Stopped'), ('running', 'Running'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('error', 'Error'), ('unknown', 'Unknown'), ('provisioning', 'Provisioning'), ('decommissioned', 'Decommissioned')], db_index=True, default='unknown', help_text='Normalized lifecycle state.', max_length=32),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metric dimensions/labels.'),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='metric_type',
            field=models.CharField(db_index=True, help_text='Type of metric (cpu_usage, memory_usage, invocation_count, etc.).', max_length=64),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='When this metric was captured.'),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of measurement (percent, mb, gb, count, ms, etc.).', max_length=32),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='value_float',
            field=models.FloatField(blank=True, help_text='Numeric metric value.', null=True),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='value_int',
            field=models.BigIntegerField(blank=True, help_text='Integer metric value (counts, bytes, etc.).', null=True),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Additional relationship metadata.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(help_text='Tag key.', max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='namespace',
            field=models.CharField(db_index=True, help_text="Tag namespace (e.g. 'environment', 'cost_center', 'application').", max_length=128),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(blank=True, default='', help_text='Tag value.', max_length=1024),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['properties'], name='idx_resource_properties_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['provider_tags'], name='idx_resource_provider_tags_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddField(
            model_name='resourcedrift',
            name='collection_run',
            field=models.ForeignKey(help_text='The collection run that detected this drift.', on_delete=django.db.models.deletion.CASCADE, related_name='drift_events', to='inventory.collectionrun'),
        ),
        migrations.AddField(
            model_name='resourcedrift',
            name='previous_collection_run',
            field=models.ForeignKey(blank=True, help_text='The prior run being compared against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_events_as_previous', to='inventory.collectionrun'),
        ),
        migrations.AddField(
            model_name='resourcedrift',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_events', to='inventory.resource'),
        ),
        migrations.AddIndex(
            model_name='resourcedrift',
            index=models.Index(fields=['resource', '-detected_at'], name='inventory_r_resourc_a2b5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcedrift',
            index=models.Index(fields=['collection_run', 'drift_type'], name='inventory_r_collect_46e2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcedrift',
            index=models.Index(fields=['drift_type', '-detected_at'], name='inventory_r_drift_t_ef3850_idx'),
        ),
    ]
