# Generated by Django 5.2.11 on 2026-02-20 09:03
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0007_drift_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Human-readable label, e.g. 'Nightly full refresh'.", max_length=255)),
                ("cron_expression", models.CharField(help_text="Standard 5-field cron expression (minute hour day month weekday). Example: '0 */6 * * *' = every 6 hours.", max_length=100)),
                ("enabled", models.BooleanField(default=True, help_text="Disabled schedules are skipped by the scheduler.")),
                ("last_run_at", models.DateTimeField(blank=True, help_text="When the last collection was triggered by this schedule.", null=True)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, help_text="Pre-computed next fire time, updated after each run.", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "name"],
            },
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_resource_properties_gin ON inventory_resource USING gin (properties jsonb_path_ops);",
            reverse_sql="DROP INDEX IF EXISTS idx_resource_properties_gin;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_resource_provider_tags_gin ON inventory_resource USING gin (provider_tags jsonb_path_ops);",
            reverse_sql="DROP INDEX IF EXISTS idx_resource_provider_tags_gin;",
        ),
        migrations.AddField(
            model_name="collectionschedule",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="inventory.provider"),
        ),
        migrations.AddIndex(
            model_name="collectionschedule",
            index=models.Index(fields=["enabled", "next_run_at"], name="inventory_c_enabled_117f01_idx"),
        ),
    ]
