# Generated by Django 5.2.11 on 2026-02-26 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0009_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AAPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable label, e.g. "Production AAP".', max_length=255)),
                ('base_url', models.URLField(help_text='Controller API base URL, e.g. https://aap.example.org', max_length=1024)),
                ('oauth_token', models.CharField(help_text='OAuth2 personal access token (stored encrypted at rest).', max_length=2048)),
                ('verify_ssl', models.BooleanField(default=True, help_text='Whether to verify SSL certificates when connecting.')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable syncing from this connection.')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, help_text='How often to run correlation sync (in minutes).')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful sync.', null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the most recent sync.', max_length=32)),
                ('last_sync_error', models.TextField(blank=True, default='', help_text='Error message from last failed sync.')),
                ('last_sync_host_count', models.PositiveIntegerField(default=0, help_text='Number of hosts found in last sync.')),
                ('last_sync_matched_count', models.PositiveIntegerField(default=0, help_text='Number of hosts matched to inventory resources in last sync.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], db_index=True, default='direct', help_text='direct (host-level SSH/WinRM) or indirect (API/fabric).', max_length=16)),
                ('correlation_key', models.CharField(help_text='The value used to match (e.g. SMBIOS UUID).', max_length=1024)),
                ('correlation_confidence', models.CharField(choices=[('exact', 'Exact'), ('probable', 'Probable')], default='exact', help_text='Match confidence: exact (UUID) or probable (heuristic).', max_length=16)),
                ('aap_host_id', models.IntegerField(help_text='Host ID in the AAP controller.')),
                ('aap_host_name', models.CharField(help_text='Hostname as known to AAP.', max_length=1024)),
                ('aap_job_id', models.IntegerField(help_text='The job execution ID in AAP.')),
                ('aap_job_name', models.CharField(blank=True, default='', help_text='Job template name.', max_length=1024)),
                ('aap_job_status', models.CharField(blank=True, default='', help_text='Job status: successful, failed, canceled, etc.', max_length=32)),
                ('aap_job_started_at', models.DateTimeField(blank=True, help_text='When the job started.', null=True)),
                ('aap_job_finished_at', models.DateTimeField(blank=True, help_text='When the job completed.', null=True)),
                ('aap_inventory_name', models.CharField(blank=True, default='', help_text='AAP inventory the host belongs to.', max_length=512)),
                ('automation_details', models.JSONField(blank=True, default=dict, help_text='Full metadata snapshot (playbook, extra_vars, etc.).')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this record was created/updated by sync.')),
            ],
            options={
                'ordering': ['-aap_job_started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=GinIndex(fields=['properties'], name='idx_resource_properties_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=GinIndex(fields=['provider_tags'], name='idx_resource_provider_tags_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddField(
            model_name='aapconnection',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aapconnection',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this connection.', on_delete=django.db.models.deletion.CASCADE, related_name='aap_connections', to='core.organization'),
        ),
        migrations.AddField(
            model_name='automationrecord',
            name='aap_connection',
            field=models.ForeignKey(help_text='Which AAP instance this record came from.', on_delete=django.db.models.deletion.CASCADE, related_name='automation_records', to='inventory.aapconnection'),
        ),
        migrations.AddField(
            model_name='automationrecord',
            name='organization',
            field=models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.CASCADE, related_name='automation_records', to='core.organization'),
        ),
        migrations.AddField(
            model_name='automationrecord',
            name='resource',
            field=models.ForeignKey(help_text='The matched inventory resource.', on_delete=django.db.models.deletion.CASCADE, related_name='automation_records', to='inventory.resource'),
        ),
        migrations.AddIndex(
            model_name='aapconnection',
            index=models.Index(fields=['organization'], name='inventory_a_organiz_fe6f32_idx'),
        ),
        migrations.AddIndex(
            model_name='aapconnection',
            index=models.Index(fields=['enabled', 'last_sync_at'], name='inventory_a_enabled_830ab8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aapconnection',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='automationrecord',
            index=models.Index(fields=['resource', '-aap_job_started_at'], name='inventory_a_resourc_077dff_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrecord',
            index=models.Index(fields=['aap_connection', 'aap_host_id'], name='inventory_a_aap_con_53da5d_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrecord',
            index=models.Index(fields=['correlation_type'], name='inventory_a_correla_2855fc_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrecord',
            index=models.Index(fields=['correlation_key'], name='inventory_a_correla_7fcea5_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrecord',
            index=models.Index(fields=['aap_job_started_at'], name='inventory_a_aap_job_74f567_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationrecord',
            unique_together={('resource', 'aap_connection', 'aap_job_id')},
        ),
    ]
